# Generated by Django 5.2.4 on 2025-08-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_setup', '0004_alter_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(default='', null=True, upload_to='assets/favicon/'),
        ),
    ]
