# Generated by Django 5.2.4 on 2025-08-06 17:50

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_setup', '0005_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(default='', null=True, upload_to='assets/favicon/', validators=[utils.model_validators.validate_png]),
        ),
    ]
